### ISSUE TITLE
search failed for "Error: failed to find exact match via binary search"

### ISSUE THREAD

**Issue by chenchampion** [erbbysam/DNSGrep#2]
hello, I try to use the project to grep the text from rapid7, the command is " go run dnsgrep.go -f fdns_a.sort.txt -i "erbbyam.com"", but the search failed for "Error: failed to find exact match via binary search". could you help to tell me what the problem ? thank you.

**Comment by erbbysam** [comment]
Are you sure the file was correctly generated? You may see this error if it was not. It will take 20+ minutes, but can you grep the file for "moc.masybbre" & share the file size you generated ?

**Comment by chenchampion** [comment]
Got it. thank you and sorry, It's my fault. close the issue.

**Comment by petetiR** [comment]
Hello and thank you for this project,

I run into the same issue, except that my file seems correctly generated.
It has a decent size :
![image](https://user-images.githubusercontent.com/28652140/111547023-d5ef7f00-8778-11eb-9e97-b8dd9e42944e.png)

Your grep test succeeds :
![image](https://user-images.githubusercontent.com/28652140/111546918-ad678500-8778-11eb-88d8-c7818ae36b2d.png)

Still the script fails :
![image](https://user-images.githubusercontent.com/28652140/111547333-472f3200-8779-11eb-895b-de741f572560.png)

I downloaded this archive : [2021-02-26-1614298023-fdns_a.json.gz](https://opendata.rapid7.com/sonar.fdns_v2/2021-02-26-1614298023-fdns_a.json.gz)
The generated file "fdns_a.sort.txt" has the following sha1 : ``fd664ca97fd581f9331eed0c6e7846fdd6a808f2``

Do you have any idea on what could cause this issue ?

**Comment by petetiR** [comment]
I forgot to mention that I'm running the project on a raspberry pi 4, maybe this makes a difference ?
